# ba0fde3d-bee7-4307-b97b-17d0d20aff50
[customizations.installer.kickstart]
contents = """

autopart --nohome --fstype=ext4
zerombr
clearpart --none --initlabel
timezone America/Los_Angeles --utc
network --hostname stillos --bootproto=dhcp --device=link --activate
rootpw --lock

%addon com_redhat_kdump --disable
%end

%post --erroronfail --log=/root/anaconda-post.log
bootc switch --mutate-in-place --transport registry quay.io/stillhq/stillos-workstation-edge:latest

rm -f /var/lib/systemd/random-seed
systemctl disable kdump.service

%end
"""

[customizations.installer.modules]
enable = [
    "org.fedoraproject.Anaconda.Modules.Localization",
    "org.fedoraproject.Anaconda.Modules.Storage",
    "org.fedoraproject.Anaconda.Modules.Timezone",
]
disable = [
    "org.fedoraproject.Anaconda.Modules.Network",
    "org.fedoraproject.Anaconda.Modules.Security",
    "org.fedoraproject.Anaconda.Modules.Services",
    "org.fedoraproject.Anaconda.Modules.Subscription",
    "org.fedoraproject.Anaconda.Modules.Users",
]
