---
name: Initial Setup
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  start:
    runs-on: ubuntu-latest
    if: github.repository != 'AlmaLinux/atomic-respin-template'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run initial setup script
        run: |
          # sed -i "/if: github.repository != 'AlmaLinux\/atomic-respin-template'/d" .github/workflows/*.yml
          rm -rf \
            .github/README.md \
            .github/workflows/auto-merge-dependabot.yml \
            .github/workflows/initial_setup.yml

      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git commit -a -m "Initial setup: remove template files"
          git push
